# Generated by Django 3.0.3 on 2021-08-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sellerapp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=20)),
            ],
        ),
    ]
