# Generated by Django 3.2.6 on 2021-08-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selname', models.CharField(max_length=50)),
                ('seladd', models.CharField(max_length=50)),
                ('selphone', models.BigIntegerField()),
                ('selemail', models.CharField(max_length=50)),
            ],
        ),
    ]
