# Generated by Django 3.2.6 on 2021-08-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller_Name', models.CharField(max_length=50)),
                ('Seller_Address', models.CharField(max_length=50)),
                ('EMail_Id', models.CharField(max_length=50)),
                ('Phone_Number', models.BigIntegerField(default=False)),
                ('Date_of_Birth', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Age', models.IntegerField(default=False)),
                ('Adhar_Number', models.BigIntegerField(default=False)),
            ],
        ),
    ]
