# Generated by Django 3.2.6 on 2021-08-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=50)),
                ('Pdetails', models.CharField(max_length=50)),
                ('Sname', models.CharField(max_length=50)),
                ('Mname', models.CharField(max_length=50)),
                ('Mdate', models.CharField(max_length=50)),
                ('Edate', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
