# Generated by Django 3.2.6 on 2021-08-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('dob', models.CharField(default='', max_length=50)),
                ('district', models.CharField(default='', max_length=50)),
                ('age', models.CharField(default='', max_length=50)),
                ('aadharnum', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
