# Generated by Django 3.2.6 on 2021-08-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pdetails', models.CharField(max_length=50)),
                ('sellername', models.CharField(max_length=50)),
                ('manufacturedate', models.DateField()),
                ('expirydate', models.DateField()),
            ],
        ),
    ]
