# Generated by Django 3.2.6 on 2021-08-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=200)),
                ('manufacturingdate', models.DateField()),
                ('expirydate', models.DateField()),
            ],
        ),
    ]
