# Generated by Django 3.2.6 on 2021-08-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('emailid', models.CharField(max_length=50)),
                ('phoneno', models.BigIntegerField()),
                ('dateofbirth', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('aadhar', models.BigIntegerField()),
            ],
        ),
    ]
