# Generated by Django 3.2.6 on 2021-08-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildnum', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField(default=0)),
                ('aadhar', models.BigIntegerField(default=0)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
