# Generated by Django 3.2.6 on 2021-08-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('Emailid', models.CharField(max_length=50)),
                ('Mobnum', models.BigIntegerField()),
                ('DOB', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('AdhaarNum', models.IntegerField()),
                ('District', models.CharField(max_length=50)),
            ],
        ),
    ]
