# Generated by Django 3.2.6 on 2021-08-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_rename_address_seller_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='Mobnum',
            new_name='MobNum',
        ),
    ]
