# Generated by Django 3.2.6 on 2021-08-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sellerapp1',
            new_name='Sellerapp',
        ),
    ]
