# Generated by Django 3.2.6 on 2021-08-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_rename_sellerapp1_sellerapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sellerapp',
            new_name='Sellerapp1',
        ),
    ]
