# Generated by Django 3.2.6 on 2021-08-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=50)),
                ('Adress', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Date_of_birth', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=50)),
                ('Adharnumber', models.CharField(max_length=40)),
            ],
        ),
    ]
