# Generated by Django 3.2.6 on 2021-08-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('add', models.CharField(default='', max_length=50)),
                ('pincode', models.IntegerField(default='')),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.BigIntegerField(default='')),
            ],
        ),
    ]
