# Generated by Django 3.2.6 on 2021-08-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prname', models.CharField(max_length=50)),
                ('prdesc', models.CharField(max_length=50)),
                ('prprice', models.BigIntegerField()),
                ('prmanfd', models.CharField(max_length=50)),
                ('prbrand', models.CharField(max_length=50)),
            ],
        ),
    ]
