# Generated by Django 3.2.6 on 2021-08-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('mobnum', models.BigIntegerField()),
                ('tripid', models.IntegerField()),
                ('tripcost', models.IntegerField()),
                ('tripplan', models.CharField(max_length=50)),
            ],
        ),
    ]
