# Generated by Django 3.2.6 on 2021-08-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pdetails',
            new_name='pdes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='edate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mdate',
        ),
    ]
