# Generated by Django 3.2.6 on 2021-08-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=50)),
                ('Productdetails', models.CharField(max_length=50)),
                ('Sellername', models.CharField(max_length=50)),
                ('ManufactureName', models.CharField(max_length=50)),
                ('ManufactureDate', models.IntegerField()),
                ('ExpiryDate', models.IntegerField()),
                ('Branch', models.CharField(max_length=50)),
            ],
        ),
    ]
