# Generated by Django 3.2.6 on 2021-08-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phoneno',
            field=models.BigIntegerField(),
        ),
    ]
