# Generated by Django 3.0.4 on 2021-08-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('saddress', models.CharField(max_length=50)),
                ('semail', models.CharField(max_length=50)),
                ('sweb', models.CharField(max_length=50)),
                ('sphone', models.CharField(max_length=50)),
                ('susername', models.CharField(max_length=50)),
                ('spwd', models.CharField(max_length=50)),
                ('scpwd', models.CharField(max_length=50)),
            ],
        ),
    ]
