# Generated by Django 3.2.6 on 2021-08-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
                ('sellername', models.CharField(max_length=50)),
                ('manufacture_name', models.CharField(max_length=50)),
                ('manufacturing_date', models.IntegerField()),
                ('expirydate', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
