# Generated by Django 3.2.6 on 2021-08-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expirydate',
            new_name='expdate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='manufacture_name',
            new_name='manfname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='manufacturing_date',
            new_name='mfgdate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='pname',
        ),
    ]
