# Generated by Django 3.2.6 on 2021-08-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shopname', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Emailid', models.CharField(max_length=50)),
                ('MobNum', models.IntegerField()),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.IntegerField()),
                ('ConfirmPassword', models.IntegerField()),
            ],
        ),
    ]
