# Generated by Django 3.2.6 on 2021-08-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('email_Id', models.CharField(max_length=50)),
                ('USER_NAME', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=50)),
                ('Confirm_password', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('phn_no', models.BigIntegerField()),
            ],
        ),
    ]
