# Generated by Django 3.0.4 on 2021-08-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rackno', models.CharField(max_length=50)),
                ('medname', models.CharField(max_length=50)),
                ('medcat', models.CharField(max_length=50)),
                ('mfgdate', models.DateField()),
                ('expdate', models.DateField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
