# Generated by Django 3.2.6 on 2021-08-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('padd', models.CharField(max_length=50)),
                ('pmob', models.CharField(max_length=50)),
            ],
        ),
    ]
