# Generated by Django 3.2.6 on 2021-08-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='pmob',
            new_name='pbg',
        ),
        migrations.AddField(
            model_name='patients',
            name='pcity',
            field=models.CharField(default='bhopal', max_length=50),
        ),
        migrations.AddField(
            model_name='patients',
            name='pdob',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AddField(
            model_name='patients',
            name='pemail',
            field=models.CharField(default='patient.mmail', max_length=50),
        ),
        migrations.AddField(
            model_name='patients',
            name='pphone',
            field=models.BigIntegerField(default=0),
        ),
    ]
