# Generated by Django 3.2.6 on 2021-08-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_alter_patients_pdob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='pphone',
            field=models.CharField(max_length=50),
        ),
    ]
