# Generated by Django 3.2.6 on 2021-08-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_alter_patients_pphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='pdob',
            field=models.CharField(max_length=50),
        ),
    ]
