# Generated by Django 3.2.6 on 2021-08-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pdetails', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('expirydate', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
