# Generated by Django 3.2.6 on 2021-08-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainName', models.CharField(max_length=50, unique=True)),
                ('trainNumber', models.CharField(max_length=20, unique=True)),
                ('fromStation', models.CharField(max_length=40)),
                ('toStation', models.CharField(max_length=40)),
                ('runningDays', models.CharField(max_length=30)),
            ],
        ),
    ]
