# Generated by Django 3.2.6 on 2021-08-19 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Product_Details', models.CharField(max_length=50)),
                ('Seller_Name', models.CharField(max_length=50)),
                ('BRAND', models.CharField(max_length=50)),
                ('Manufacturer_Name', models.CharField(max_length=50)),
                ('Manufacturing_Date', models.CharField(max_length=50)),
                ('Expire_Date', models.DateTimeField(default=datetime.datetime(2021, 8, 19, 23, 41, 10, 528124))),
                ('Price', models.IntegerField(default=False)),
            ],
        ),
    ]
