# Generated by Django 3.2.6 on 2021-08-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dogid', models.CharField(max_length=50)),
                ('Dname', models.CharField(max_length=50)),
                ('Dage', models.CharField(max_length=50)),
                ('Dprice', models.CharField(max_length=50)),
            ],
        ),
    ]
