# Generated by Django 3.2.6 on 2021-08-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rno',
            field=models.BigIntegerField(),
        ),
    ]
