# Generated by Django 3.2.6 on 2021-08-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=50)),
                ('mname', models.CharField(default='', max_length=50)),
                ('mduration', models.CharField(default='', max_length=50)),
                ('mtimings', models.CharField(default='', max_length=50)),
                ('totalseats', models.CharField(default='', max_length=50)),
                ('audi', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
