# Generated by Django 3.2.6 on 2021-08-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roomrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomclass', models.CharField(max_length=50)),
                ('classprice', models.BigIntegerField()),
                ('nigths', models.IntegerField()),
                ('roomno', models.IntegerField()),
            ],
        ),
    ]
