# Generated by Django 3.2.6 on 2021-08-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(default='', max_length=50)),
                ('saddress', models.CharField(default='', max_length=50)),
                ('semail', models.CharField(default='', max_length=50)),
                ('swebsite', models.CharField(default='', max_length=50)),
                ('sphone', models.CharField(default='', max_length=50)),
                ('susername', models.CharField(default='', max_length=50)),
                ('spassword', models.CharField(default='', max_length=50)),
                ('scpassword', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
