# Generated by Django 3.2.6 on 2021-08-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=50)),
                ('dadd', models.CharField(max_length=50)),
                ('dmob', models.CharField(max_length=50)),
                ('did', models.CharField(max_length=50)),
            ],
        ),
    ]
