# Generated by Django 3.2.6 on 2021-08-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='did',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='dmob',
        ),
        migrations.AddField(
            model_name='doctors',
            name='dcity',
            field=models.CharField(default='bhopal', max_length=50),
        ),
        migrations.AddField(
            model_name='doctors',
            name='dcont',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctors',
            name='demail',
            field=models.CharField(default='hospital@bansal.com', max_length=50),
        ),
        migrations.AddField(
            model_name='doctors',
            name='dspecial',
            field=models.CharField(default='dentist', max_length=50),
        ),
    ]
