# Generated by Django 3.2.6 on 2021-08-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sellermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('date', models.DateField()),
                ('district', models.CharField(max_length=50)),
                ('adhar', models.CharField(max_length=50)),
            ],
        ),
    ]
