# Generated by Django 3.2.6 on 2021-08-19 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 19, 22, 13, 4, 782670)),
        ),
    ]
