# Generated by Django 3.2.6 on 2021-08-19 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_alter_sellermodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
