# Generated by Django 3.2.6 on 2021-08-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_alter_sellermodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellermodel',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
